### ISSUE TITLE
Custom role action documentation missing some feature flags

### ISSUE THREAD

**Issue by lmmarsano** [launchdarkly/LaunchDarkly-Docs#77]
[This section](https://github.com/launchdarkly/LaunchDarkly-Docs/blob/master/src/content/topics/home/account-security/custom-roles/actions.mdx#feature-flags-actions) is missing some feature flags listed in the UI.
GET https://app.launchdarkly.com/internal/actions includes
``` yaml
- description: Create new feature flags
  action: createFlag
- description: Delete a feature flag
  action: deleteFlag
- description: Clone a feature flag
  action: cloneFlag
- description: Rename a feature flag
  action: updateName
- description: Trigger the kill switch for a feature flag
  action: updateOn
- description: Update the description of a feature flag
  action: updateDescription
- description: Change whether the feature flag is available to front-end code via the JavaScript SDK
  action: updateIncludeInSnippet
- description: Change whether the feature flag is available to client-side SDKs
  action: updateClientSideFlagAvailability
- description: Mark a flag temporary or permanent
  action: updateTemporary
- description: Change the tags associated with a feature flag
  action: updateTags
- description: Change a flag's prerequisites
  action: updatePrerequisites
- description: Change a flag's individual user targeting rules
  action: updateTargets
- description: Change a flag's custom targeting rules
  action: updateRules
- description: Change the flag's default rule
  action: updateFallthrough
- description: Change the flag's variations
  action: updateFlagVariations
- description: Change the default variations used by newly created environments for a feature flag
  action: updateFlagDefaultVariations
- description: Change the variation returned when the kill switch is set to off
  action: updateOffVariation
- description: Change the flag's maintainer
  action: updateMaintainer
- description: Start or stop an A/B testing experiment
  action: updateAttachedGoals
- description: Create an experiment
  action: createExperiment
- description: Delete an experiment
  action: deleteExperiment
- description: Delete experiment results
  action: deleteExperimentResults
- description: Start or stop an experiment in an environment
  action: updateExperimentActive
- description: Change a flag's baseline variation for experiments
  action: updateExperimentBaseline
- description: Change a flag's custom properties
  action: updateFlagCustomProperties
- description: Reset the experiment results for a flag in a given environment
  action: deleteFlagAttachedGoalResults
- description: Copy settings from a feature flag
  action: copyFlagConfigFrom
- description: Copy settings to a feature flag
  action: copyFlagConfigTo
- description: Update a feature flag's salt
  action: updateFlagSalt
- description: Change whether to send detailed event information for a flag in a given environment
  action: updateTrackEvents
- description: Change whether to send detailed event information for a flag in a given environment when the fallthrough variation was selected
  action: updateFlagFallthroughTrackEvents
- description: Change whether a flag is archived
  action: updateGlobalArchived
- description: Change a flag's expiring custom targeting rules
  action: updateExpiringRules
- description: Change a flag's expiring individual user targeting rules
  action: updateExpiringTargets
- description: Change a flag's feature workflows
  action: updateFeatureWorkflows
- description: Change the scheduled updates on a feature flag
  action: updateScheduledChanges
- description: Create a new trigger or edit existing triggers
  action: updateTriggers
- description: Request approval on changes
  action: createApprovalRequest
- description: Update approval requests
  action: updateApprovalRequest
- description: Delete approval requests
  action: deleteApprovalRequest
- description: Approve changes on approval requests
  action: reviewApprovalRequest
- description: Can apply the request changes once reviewed
  action: applyApprovalRequest
```
I'm most interested in actions that "impact all environments", since they'll need special handling.
Might be nice to order them alphabetically, too.

Could you document them all?
Same for actions on all other resources, too?
